package com.beatus.billlive.repository;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Component;

import com.beatus.billlive.domain.model.BillData;
import com.google.firebase.database.ChildEventListener;
import com.google.firebase.database.DataSnapshot;
import com.google.firebase.database.DatabaseError;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.ValueEventListener;


@Component("billRepository")
public class BillRepository {
	
	private static final Logger logger = LoggerFactory.getLogger(BillRepository.class);

	@Autowired
    @Qualifier(value = "databaseReference")
    private DatabaseReference databaseReference;
	
	public String isAdded = "N";
	public String isUpdated = "N";
	public String isDeleted = "N";
	
	private BillData billData = null;
	
	List<BillData> billsList = new ArrayList<BillData>();
	
	public String addBill(BillData billData) {
		try {
			DatabaseReference billsRef = databaseReference.child("bills");
			Map<String, BillData> bill = new HashMap<String, BillData>();
			// Generate a reference to a new location and add some data using push()
			DatabaseReference billsPostRef = billsRef.push();
			// Get the unique ID generated by a push()
			String postId = billsPostRef.getKey();
			billData.setPostId(postId);
			bill.put(billData.getUid(), billData);
			billsPostRef.setValue(billData, new DatabaseReference.CompletionListener() {
			    @Override
			    public void onComplete(DatabaseError databaseError, DatabaseReference databaseReference) {
			        if (databaseError != null) {
			            System.out.println("Data could not be saved " + databaseError.getMessage() + " " + billData.getUid());
			            isAdded = "N";
			        } else {
			        	logger.info("Bill saved successfully, Bill Details="+billData.getUid());
			        	isAdded = "Y";
					}
			    }
			});
			return isAdded;
		} catch (Exception e) {
			return isAdded;	
		}
	}

	public String updateBill(BillData billData) {
		try {
			DatabaseReference billsRef = databaseReference.child("bills");
			Map<String, Object> billUpdates = new HashMap<String, Object>();
			billUpdates.put(billData.getUid(), billData);
			billsRef.updateChildren(billUpdates, new DatabaseReference.CompletionListener() {
			    @Override
			    public void onComplete(DatabaseError databaseError, DatabaseReference databaseReference) {
			        if (databaseError != null) {
			            System.out.println("Data could not be updated " + databaseError.getMessage() + " " + billData.getUid());
			            isUpdated = "N";
			        } else {
			        	logger.info("Bill updated successfully, Bill Details="+billData.getUid());
			        	isUpdated = "Y";
					}
			    }
			});
			return isUpdated;
		} catch (Exception e) {
			return isUpdated;	
		}
	}
	
	public String removeBill(String uid) {
		try {
			DatabaseReference billsRef = databaseReference.child("bills");
			Map<String, Object> billUpdates = new HashMap<String, Object>();
			billUpdates.put(uid, null);
			billsRef.updateChildren(billUpdates, new DatabaseReference.CompletionListener() {
			    @Override
			    public void onComplete(DatabaseError databaseError, DatabaseReference databaseReference) {
			        if (databaseError != null) {
			            System.out.println("Data could not be removed " + databaseError.getMessage() + " " + uid);
			            isDeleted = "N";
			        } else {
			        	logger.info("Bill removed successfully, Bill Details="+uid);
			        	isDeleted = "Y";
					}
			    }
			});
			return isDeleted;
		} catch (Exception e) {
			return isDeleted;	
		}
	}
	
	public BillData getBillById(String uId) {
		DatabaseReference billDataRef = databaseReference.child("bills");
		billData = null;
		billDataRef.orderByChild("uid").equalTo(uId).addChildEventListener(new ChildEventListener() {
		    @Override
		    public void onChildAdded(DataSnapshot dataSnapshot, String prevChildKey) {
		        billData = dataSnapshot.getValue(BillData.class);
		        System.out.println(dataSnapshot.getKey() + " was " + billData.getUid());
		    }

			@Override
			public void onChildChanged(DataSnapshot snapshot, String previousChildName) {
				
			}

			@Override
			public void onChildRemoved(DataSnapshot snapshot) {
				
			}

			@Override
			public void onChildMoved(DataSnapshot snapshot, String previousChildName) {
				
			}

			@Override
			public void onCancelled(DatabaseError error) {
				
			}
		});
		logger.info("Bill loaded successfully, Bill details=" + billData);
		return billData;
	}
	
	public List<BillData> getAllBills() {
		DatabaseReference billDataRef = databaseReference.child("bills");
		billDataRef.addValueEventListener(new ValueEventListener() {
		    public void onDataChange(DataSnapshot billSnapshot) {
		    	billsList.clear();
		        for (DataSnapshot billPostSnapshot: billSnapshot.getChildren()) {
		            BillData billData = billPostSnapshot.getValue(BillData.class);
		            billsList.add(billData);
		        }
		    }
		    
			@Override
			public void onCancelled(DatabaseError error) {
				
			}
		});
		return billsList;
	}


}