package com.beatus.billlive.repository;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Component;

import com.beatus.billlive.domain.model.BillData;
import com.beatus.billlive.service.exception.BillliveServiceException;
import com.beatus.billlive.validation.exception.BillValidationException;
import com.google.firebase.database.ChildEventListener;
import com.google.firebase.database.DataSnapshot;
import com.google.firebase.database.DatabaseError;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.ValueEventListener;


@Component("billRepository")
public class BillRepository {
	
	private static final Logger logger = LoggerFactory.getLogger(BillRepository.class);

	@Autowired
    @Qualifier(value = "databaseReference")
    private DatabaseReference databaseReference;
	
	public String isAdded = "N";
	public String isUpdated = "N";
	public String isDeleted = "N";
	
	private BillData billData = null;
	
	List<BillData> billsList = new ArrayList<BillData>();
	
	public String addBill(BillData billData) {
		try {
        	logger.info("In addBill method of BillRepository");
			DatabaseReference billsRef = databaseReference.child("bills").child(billData.getCompanyId());
			Map<String, BillData> bill = new HashMap<String, BillData>();
			// Generate a reference to a new location and add some data using push()
			DatabaseReference billsPostRef = billsRef.push();
			// Get the unique ID generated by a push()
			String postId = billsPostRef.getKey();
			billData.setPostId(postId);
			bill.put(billData.getBillNumber(), billData);
			billsPostRef.setValue(billData, new DatabaseReference.CompletionListener() {
			    @Override
			    public void onComplete(DatabaseError databaseError, DatabaseReference databaseReference) {
			        if (databaseError != null) {
			            System.out.println("Data could not be saved " + databaseError.getMessage() + " " + billData.getUid());
			        } else {
			        	logger.info("Bill saved successfully, Bill Details="+billData.getUid());
			        }
			    }
			});
			return billData.getBillNumber();
		} catch (Exception e) {
			throw e;	
		}
	}

	public String updateBill(BillData billData) throws BillValidationException, BillliveServiceException {
		try {
			logger.info("In updateBill method of BillRepository");
			DatabaseReference billsRef = databaseReference.child("bills").child(billData.getCompanyId());
			Map<String, Object> billUpdates = new HashMap<String, Object>();
			billUpdates.put(billData.getBillNumber(), billData);
			billsRef.updateChildren(billUpdates, new DatabaseReference.CompletionListener() {
			    @Override
			    public void onComplete(DatabaseError databaseError, DatabaseReference databaseReference) {
			        if (databaseError != null) {
			            System.out.println("Data could not be updated " + databaseError.getMessage() + " " + billData.getUid());
			            isUpdated = "N";
			        } else {
			        	logger.info("Bill updated successfully, Bill Details = "+billData.getUid());
			        	isUpdated = "Y";
					}
			    }
			});
			return isUpdated;
		} catch (Exception e) {
			throw new BillliveServiceException("Billlive Service exception at UpdateBill method of BillRepository. Error message : " + e.getMessage());
		}
	}
	
	public String removeBill(String billNumber, String companyId) {
		try {
			logger.info("In removeBill method of BillRepository");
			DatabaseReference billsRef = databaseReference.child("bills").child(companyId);
			Map<String, Object> billUpdates = new HashMap<String, Object>();
			billUpdates.put(billNumber, null);
			billsRef.updateChildren(billUpdates, new DatabaseReference.CompletionListener() {
			    @Override
			    public void onComplete(DatabaseError databaseError, DatabaseReference databaseReference) {
			        if (databaseError != null) {
			            System.out.println("Data could not be removed " + databaseError.getMessage() + " " + billNumber);
			            isDeleted = "N";
			        } else {
			        	logger.info("Bill removed successfully, Bill Details="+billNumber);
			        	isDeleted = "Y";
					}
			    }
			});
			return isDeleted;
		} catch (Exception e) {
			return isDeleted;	
		}
	}
	
	public BillData getBillByBillNumber(String companyId, String billNumber) {
		logger.info("In getBillByBillNumber method of BillRepository");
		DatabaseReference billDataRef = databaseReference.child("bills").child(companyId);
		billData = null;
		billDataRef.orderByChild("billNumber").equalTo(billNumber).addChildEventListener(new ChildEventListener() {
		    @Override
		    public void onChildAdded(DataSnapshot dataSnapshot, String prevChildKey) {
		        billData = dataSnapshot.getValue(BillData.class);
		        System.out.println(dataSnapshot.getKey() + " was " + billData.getUid());
		    }

			@Override
			public void onChildChanged(DataSnapshot snapshot, String previousChildName) {
				
			}

			@Override
			public void onChildRemoved(DataSnapshot snapshot) {
				
			}

			@Override
			public void onChildMoved(DataSnapshot snapshot, String previousChildName) {
				
			}

			@Override
			public void onCancelled(DatabaseError error) {
				
			}
		});
		logger.info("Bill loaded successfully, Bill details=" + billData);
		return billData;
	}
	
	public List<BillData> getAllBillsBasedOnCompanyId(String companyId) {
		DatabaseReference billDataRef = databaseReference.child("bills").child(companyId);
		billDataRef.addValueEventListener(new ValueEventListener() {
		    public void onDataChange(DataSnapshot billSnapshot) {
		    	billsList.clear();
		        for (DataSnapshot billPostSnapshot: billSnapshot.getChildren()) {
		            BillData billData = billPostSnapshot.getValue(BillData.class);
		            billsList.add(billData);
		        }
		    }
		    
			@Override
			public void onCancelled(DatabaseError error) {
				
			}
		});
		return billsList;
	}
	
	public List<BillData> getAllBillsInAMonth(String companyId, String year, String month) {
		logger.info("In getAllBillsInAMonth method of BillRepository");
		DatabaseReference billDataRef = databaseReference.child("bills").child(companyId);
		billDataRef.orderByChild("year").equalTo(year).orderByChild("month").equalTo(month).addValueEventListener(new ValueEventListener() {
		    public void onDataChange(DataSnapshot billSnapshot) {
		    	billsList.clear();
		        for (DataSnapshot billPostSnapshot: billSnapshot.getChildren()) {
		            BillData billData = billPostSnapshot.getValue(BillData.class);
		            billsList.add(billData);
		        }
		    }
		    
			@Override
			public void onCancelled(DatabaseError error) {
				
			}
		});
		return billsList;
	}
	
	public List<BillData> getAllBillsInAYear(String companyId, String year) {
		logger.info("In getAllBillsInAYear method of BillRepository");
		DatabaseReference billDataRef = databaseReference.child("bills").child(companyId);
		billDataRef.orderByChild("year").equalTo(year).addValueEventListener(new ValueEventListener() {
		    public void onDataChange(DataSnapshot billSnapshot) {
		    	billsList.clear();
		        for (DataSnapshot billPostSnapshot: billSnapshot.getChildren()) {
		            BillData billData = billPostSnapshot.getValue(BillData.class);
		            billsList.add(billData);
		        }
		    }
		    
			@Override
			public void onCancelled(DatabaseError error) {
				
			}
		});
		return billsList;
	}
	
	public List<BillData> getAllBillsInADay(String companyId, String year, String month, String day) {
		logger.info("In getAllBillsInADay method of BillRepository");
		DatabaseReference billDataRef = databaseReference.child("bills").child(companyId);
		billDataRef.orderByChild("year").equalTo(year).orderByChild("month").equalTo(month).orderByChild("day").equalTo(day).addValueEventListener(new ValueEventListener() {
		    public void onDataChange(DataSnapshot billSnapshot) {
		    	billsList.clear();
		        for (DataSnapshot billPostSnapshot: billSnapshot.getChildren()) {
		            BillData billData = billPostSnapshot.getValue(BillData.class);
		            billsList.add(billData);
		        }
		    }
		    
			@Override
			public void onCancelled(DatabaseError error) {
				
			}
		});
		return billsList;
	}
	
	public List<BillData> getAllBills(String companyId) {
		logger.info("In getAllBills method of BillRepository");
		DatabaseReference billDataRef = databaseReference.child("bills").child(companyId);
		billDataRef.orderByChild("companyId").equalTo(companyId).addValueEventListener(new ValueEventListener() {
		    public void onDataChange(DataSnapshot billSnapshot) {
		    	billsList.clear();
		        for (DataSnapshot billPostSnapshot: billSnapshot.getChildren()) {
		            BillData billData = billPostSnapshot.getValue(BillData.class);
		            billsList.add(billData);
		        }
		    }
		    
			@Override
			public void onCancelled(DatabaseError error) {
				
			}
		});
		return billsList;
	}


}