package com.beatus.billlive.repository;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Component;

import com.beatus.billlive.domain.model.ItemData;
import com.beatus.billlive.repository.data.listener.OnGetDataListener;
import com.google.firebase.database.DataSnapshot;
import com.google.firebase.database.DatabaseError;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.ValueEventListener;


@Component("itemRepository")
public class ItemRepository {
	
	private static final Logger logger = LoggerFactory.getLogger(ItemRepository.class);

	@Autowired
    @Qualifier(value = "databaseReference")
    private DatabaseReference databaseReference;
	
	public String isAdded = "N";
	public String isUpdated = "N";
	public String isDeleted = "N";
	
	private ItemData itemData = null;
	
	List<ItemData> itemsList = new ArrayList<ItemData>();
	
	public String addItem(ItemData itemData) {
		try {
			DatabaseReference itemsRef = databaseReference.child("items").child(itemData.getCompanyId());
			Map<String, ItemData> item = new HashMap<String, ItemData>();
			// Generate a reference to a new location and add some data using push()
			DatabaseReference itemsPostRef = itemsRef.push();
			// Get the unique ID generated by a push()
			String postId = itemsPostRef.getKey();
			itemData.setPostId(postId);
			item.put(itemData.getItemId(), itemData);
			itemsPostRef.setValue(itemData, new DatabaseReference.CompletionListener() {
			    @Override
			    public void onComplete(DatabaseError databaseError, DatabaseReference databaseReference) {
			        if (databaseError != null) {
			        	logger.info("Data could not be saved " + databaseError.getMessage() + " " + itemData.getItemId());
			            isAdded = "N";
			        } else {
			        	logger.info("Item saved successfully, Item Details="+itemData.getItemId());
			        	isAdded = "Y";
					}
			    }
			});
			return isAdded;
		} catch (Exception e) {
			return isAdded;	
		}
	}

	public String updateItem(ItemData itemData) {
		try {
			DatabaseReference itemsRef = databaseReference.child("items").child(itemData.getCompanyId());
			Map<String, Object> itemUpdates = new HashMap<String, Object>();
			itemUpdates.put(itemData.getItemId(), itemData);
			itemsRef.updateChildren(itemUpdates, new DatabaseReference.CompletionListener() {
			    @Override
			    public void onComplete(DatabaseError databaseError, DatabaseReference databaseReference) {
			        if (databaseError != null) {
			            System.out.println("Data could not be updated " + databaseError.getMessage() + " " + itemData.getItemId());
			            isUpdated = "N";
			        } else {
			        	logger.info("Item updated successfully, Item Details="+itemData.getItemId());
			        	isUpdated = "Y";
					}
			    }
			});
			return isUpdated;
		} catch (Exception e) {
			return isUpdated;	
		}
	}
	
	public String removeItem(String companyId, String itemId) {
		try {
			DatabaseReference itemsRef = databaseReference.child("items").child(companyId);
			Map<String, Object> itemUpdates = new HashMap<String, Object>();
			itemUpdates.put(itemId, null);
			itemsRef.updateChildren(itemUpdates, new DatabaseReference.CompletionListener() {
			    @Override
			    public void onComplete(DatabaseError databaseError, DatabaseReference databaseReference) {
			        if (databaseError != null) {
			            System.out.println("Data could not be removed " + databaseError.getMessage() + " " + itemId);
			            isDeleted = "N";
			        } else {
			        	logger.info("Item removed successfully, Item Details="+itemId);
			        	isDeleted = "Y";
					}
			    }
			});
			return isDeleted;
		} catch (Exception e) {
			return isDeleted;	
		}
	}
	
	public ItemData getItemById(String companyId, String itemId, OnGetDataListener listener) {
		listener.onStart();
		DatabaseReference itemDataRef = databaseReference.child("items").child(companyId);
		itemData = null;
		itemDataRef.orderByChild("itemId").equalTo(itemId).addListenerForSingleValueEvent(new ValueEventListener() {
		    @Override
		    public void onDataChange(DataSnapshot dataSnapshot) {
		    	listener.onSuccess(dataSnapshot);
		    }

		    @Override
		    public void onCancelled(DatabaseError databaseError) {
		    	listener.onFailed(databaseError);
		    }
		});
		logger.info("Item loaded successfully, Item details=" + itemData);
		return itemData;
	}
	
	public List<ItemData> getAllItems(String companyId, OnGetDataListener listener) {
		DatabaseReference itemDataRef = databaseReference.child("items").child(itemData.getCompanyId());
		itemDataRef.orderByChild("companyId").equalTo(companyId).addListenerForSingleValueEvent(new ValueEventListener() {
		    @Override
		    public void onDataChange(DataSnapshot dataSnapshot) {
		    	listener.onSuccess(dataSnapshot);
		    }

		    @Override
		    public void onCancelled(DatabaseError databaseError) {
		    	listener.onFailed(databaseError);
		    }
		});
		return itemsList;
	}
}